name: jadwal
description: تطبيق جدول - تطبيق جداول بيانات متكامل للأجهزة اللوحية
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # UI & Canvas
  flutter_riverpod: ^2.4.9
  syncfusion_flutter_datagrid: ^24.1.41
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

  # Data & .xlsx Engines
  excel: ^3.0.0
  path_provider: ^2.1.1
  hive_flutter: ^1.1.0

  # Core & AI API
  google_generative_ai: ^0.2.0

  # Utilities
  uuid: ^4.2.1
  collection: ^1.18.0
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
